apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 767397735708.dkr.ecr.eu-west-3.amazonaws.com/backend-image:47
          ports:
            - containerPort: 3001
